2024-03-22 00:54:26,999 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 00:54:27,007 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 00:54:31,898 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 00:54:35,842 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 00:54:36,997 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 00:54:37,050 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 00:54:52,611 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 00:55:02,179 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 00:55:02,289 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) done      Extract()
2024-03-22 00:55:02,291 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 00:55:02,294 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 00:55:02,294 - DEBUG - Asking scheduler for work...
2024-03-22 00:55:02,297 - DEBUG - Pending tasks: 1
2024-03-22 00:55:02,297 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) running   Load()
2024-03-22 00:55:05,778 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 00:55:05,906 - INFO - LOAD airports_data - SUCCESS
2024-03-22 00:58:12,580 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:02:53,560 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:02:53,581 - ERROR - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 225, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 376, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:02:53,630 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:02:53,634 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:02:53,635 - DEBUG - Asking scheduler for work...
2024-03-22 01:02:53,637 - DEBUG - Done
2024-03-22 01:02:53,637 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:02:53,638 - INFO - Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:02:53,639 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 00:54:26,999 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 00:54:27,007 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 00:54:31,898 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 00:54:35,842 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 00:54:36,997 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 00:54:37,050 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 00:54:52,611 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 00:55:02,179 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 00:55:02,289 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) done      Extract()
2024-03-22 00:55:02,291 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 00:55:02,294 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 00:55:02,294 - DEBUG - Asking scheduler for work...
2024-03-22 00:55:02,297 - DEBUG - Pending tasks: 1
2024-03-22 00:55:02,297 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) running   Load()
2024-03-22 00:55:05,778 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 00:55:05,906 - INFO - LOAD airports_data - SUCCESS
2024-03-22 00:58:12,580 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:02:53,560 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:02:53,581 - ERROR - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 225, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 376, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:02:53,630 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:02:53,634 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:02:53,635 - DEBUG - Asking scheduler for work...
2024-03-22 01:02:53,637 - DEBUG - Done
2024-03-22 01:02:53,637 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:02:53,638 - INFO - Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:02:53,639 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 00:54:26,999 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 00:54:27,007 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 00:54:31,898 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 00:54:35,842 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 00:54:36,997 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 00:54:37,050 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 00:54:52,611 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 00:55:02,179 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 00:55:02,289 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) done      Extract()
2024-03-22 00:55:02,291 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 00:55:02,294 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 00:55:02,294 - DEBUG - Asking scheduler for work...
2024-03-22 00:55:02,297 - DEBUG - Pending tasks: 1
2024-03-22 00:55:02,297 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) running   Load()
2024-03-22 00:55:05,778 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 00:55:05,906 - INFO - LOAD airports_data - SUCCESS
2024-03-22 00:58:12,580 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:02:53,560 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:02:53,581 - ERROR - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 225, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 376, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:02:53,630 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:02:53,634 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:02:53,635 - DEBUG - Asking scheduler for work...
2024-03-22 01:02:53,637 - DEBUG - Done
2024-03-22 01:02:53,637 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:02:53,638 - INFO - Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:02:53,639 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 00:54:26,999 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 00:54:27,007 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 00:54:31,898 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 00:54:35,842 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 00:54:36,997 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 00:54:37,050 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 00:54:52,611 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 00:55:02,179 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 00:55:02,289 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) done      Extract()
2024-03-22 00:55:02,291 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 00:55:02,294 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 00:55:02,294 - DEBUG - Asking scheduler for work...
2024-03-22 00:55:02,297 - DEBUG - Pending tasks: 1
2024-03-22 00:55:02,297 - INFO - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) running   Load()
2024-03-22 00:55:05,778 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 00:55:05,906 - INFO - LOAD airports_data - SUCCESS
2024-03-22 00:58:12,580 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:02:53,560 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:02:53,581 - ERROR - [pid 5473] Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 225, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 376, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:02:53,630 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:02:53,634 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:02:53,635 - DEBUG - Asking scheduler for work...
2024-03-22 01:02:53,637 - DEBUG - Done
2024-03-22 01:02:53,637 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:02:53,637 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:02:53,638 - INFO - Worker Worker(salt=1265043179, workers=1, host=DESKTOP-V42S030, username=laode, pid=5473) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:02:53,639 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 01:05:20,087 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:05:20,093 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:05:25,218 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:05:30,662 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:05:33,378 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:05:33,415 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:05:49,281 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:05:57,539 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:05:57,653 - INFO - [pid 12148] Worker Worker(salt=2915877304, workers=1, host=DESKTOP-V42S030, username=laode, pid=12148) done      Extract()
2024-03-22 01:05:57,654 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:05:57,657 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 01:05:57,657 - DEBUG - Asking scheduler for work...
2024-03-22 01:05:57,660 - DEBUG - Done
2024-03-22 01:05:57,660 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:05:57,660 - INFO - Worker Worker(salt=2915877304, workers=1, host=DESKTOP-V42S030, username=laode, pid=12148) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:05:57,662 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 complete ones were encountered:
    - 1 Load()
* 1 ran successfully:
    - 1 Extract()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-22 01:08:35,382 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:08:35,390 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:08:40,087 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:08:44,244 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:08:45,241 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:08:45,260 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:09:01,088 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:09:10,397 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:09:10,529 - INFO - [pid 14083] Worker Worker(salt=2754552098, workers=1, host=DESKTOP-V42S030, username=laode, pid=14083) done      Extract()
2024-03-22 01:09:10,532 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:09:10,537 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 01:09:10,537 - DEBUG - Asking scheduler for work...
2024-03-22 01:09:10,542 - DEBUG - Pending tasks: 1
2024-03-22 01:09:10,542 - INFO - [pid 14083] Worker Worker(salt=2754552098, workers=1, host=DESKTOP-V42S030, username=laode, pid=14083) running   Load()
2024-03-22 01:09:14,336 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 01:09:14,443 - INFO - LOAD airports_data - SUCCESS
2024-03-22 01:12:24,973 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:17:17,214 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:17:17,407 - ERROR - [pid 14083] Worker Worker(salt=2754552098, workers=1, host=DESKTOP-V42S030, username=laode, pid=14083) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 219, in run
    cur_dwh.execute(upsert_ticket_flights_query.format(
psycopg2.errors.ForeignKeyViolation: insert or update on table "ticket_flights" violates foreign key constraint "ticket_flights_flight_id_fkey"
DETAIL:  Key (flight_id)=(30625) is not present in table "flights".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 377, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:17:17,526 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:17:17,531 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:17:17,531 - DEBUG - Asking scheduler for work...
2024-03-22 01:17:17,533 - DEBUG - Done
2024-03-22 01:17:17,533 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:17:17,533 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:17:17,534 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:17:17,534 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:17:17,534 - INFO - Worker Worker(salt=2754552098, workers=1, host=DESKTOP-V42S030, username=laode, pid=14083) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:17:17,535 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 01:23:11,323 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:23:11,329 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:23:16,452 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:23:20,299 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:23:21,301 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:23:21,322 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:23:37,736 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:23:47,165 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:23:47,292 - INFO - [pid 21902] Worker Worker(salt=5858009446, workers=1, host=DESKTOP-V42S030, username=laode, pid=21902) done      Extract()
2024-03-22 01:23:47,293 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:23:47,297 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-22 01:23:47,298 - DEBUG - Asking scheduler for work...
2024-03-22 01:23:47,302 - DEBUG - Pending tasks: 1
2024-03-22 01:23:47,302 - INFO - [pid 21902] Worker Worker(salt=5858009446, workers=1, host=DESKTOP-V42S030, username=laode, pid=21902) running   Load()
2024-03-22 01:23:51,402 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 01:23:51,619 - INFO - LOAD airports_data - SUCCESS
2024-03-22 01:26:57,380 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:31:45,137 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:31:45,321 - ERROR - [pid 21902] Worker Worker(salt=5858009446, workers=1, host=DESKTOP-V42S030, username=laode, pid=21902) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 222, in run
    cur_dwh.execute(upsert_ticket_flights_query.format(
psycopg2.errors.ForeignKeyViolation: insert or update on table "ticket_flights" violates foreign key constraint "ticket_flights_flight_id_fkey"
DETAIL:  Key (flight_id)=(30625) is not present in table "flights".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 378, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:31:45,414 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-22 01:31:45,418 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-22 01:31:45,419 - DEBUG - Asking scheduler for work...
2024-03-22 01:31:45,421 - DEBUG - Done
2024-03-22 01:31:45,421 - DEBUG - There are no more tasks to run at this time
2024-03-22 01:31:45,421 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-22 01:31:45,422 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-22 01:31:45,422 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-22 01:31:45,422 - INFO - Worker Worker(salt=5858009446, workers=1, host=DESKTOP-V42S030, username=laode, pid=21902) was stopped. Shutting down Keep-Alive thread
2024-03-22 01:31:45,423 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-22 01:34:47,792 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:34:47,807 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:34:52,909 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:34:57,134 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:34:58,247 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:34:58,272 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:35:15,388 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:35:24,689 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:35:24,825 - INFO - [pid 28482] Worker Worker(salt=4572306550, workers=5, host=DESKTOP-V42S030, username=laode, pid=28471) done      Extract()
2024-03-22 01:35:29,073 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 01:35:29,192 - INFO - LOAD airports_data - SUCCESS
2024-03-22 01:38:38,627 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:42:52,585 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:42:52,623 - ERROR - [pid 29097] Worker Worker(salt=4572306550, workers=5, host=DESKTOP-V42S030, username=laode, pid=28471) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 228, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 378, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:34:47,792 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:34:47,807 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:34:52,909 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:34:57,134 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:34:58,247 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:34:58,272 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:35:15,388 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:35:24,689 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:35:24,825 - INFO - [pid 28482] Worker Worker(salt=4572306550, workers=5, host=DESKTOP-V42S030, username=laode, pid=28471) done      Extract()
2024-03-22 01:35:29,073 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 01:35:29,192 - INFO - LOAD airports_data - SUCCESS
2024-03-22 01:38:38,627 - INFO - LOAD bookings - SUCCESS
2024-03-22 01:42:52,585 - INFO - LOAD tickets - SUCCESS
2024-03-22 01:42:52,623 - ERROR - [pid 29097] Worker Worker(salt=4572306550, workers=5, host=DESKTOP-V42S030, username=laode, pid=28471) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 228, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 378, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 01:54:55,983 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 01:54:55,988 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 01:55:01,124 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 01:55:07,315 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 01:55:08,936 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 01:55:08,961 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 01:55:24,740 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 01:55:35,121 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 01:55:35,259 - INFO - [pid 41795] Worker Worker(salt=3394330393, workers=5, host=DESKTOP-V42S030, username=laode, pid=41784) done      Extract()
2024-03-22 01:55:39,721 - ERROR - [pid 42416] Worker Worker(salt=3394330393, workers=5, host=DESKTOP-V42S030, username=laode, pid=41784) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 113, in run
    cur_dwh.execute(upsert_aircrafts_data_query.format(
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 378, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:00:44,503 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:00:44,508 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:00:49,781 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:00:54,160 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:00:55,986 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:00:56,014 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:01:11,879 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:01:20,701 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:01:20,837 - INFO - [pid 45591] Worker Worker(salt=8941014221, workers=5, host=DESKTOP-V42S030, username=laode, pid=45575) done      Extract()
2024-03-22 02:01:24,767 - ERROR - [pid 46187] Worker Worker(salt=8941014221, workers=5, host=DESKTOP-V42S030, username=laode, pid=45575) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 113, in run
    cur_dwh.execute(upsert_aircrafts_data_query.format(
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:04:40,994 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:04:41,001 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:04:46,280 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:04:50,690 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:04:51,949 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:04:51,969 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:05:05,135 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:05:13,375 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:05:13,528 - INFO - [pid 48837] Worker Worker(salt=9340185522, workers=5, host=DESKTOP-V42S030, username=laode, pid=48826) done      Extract()
2024-03-22 02:05:17,283 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 02:05:17,400 - INFO - LOAD airports_data - SUCCESS
2024-03-22 02:08:00,510 - INFO - LOAD bookings - SUCCESS
2024-03-22 02:12:36,785 - ERROR - [pid 49395] Worker Worker(salt=9340185522, workers=5, host=DESKTOP-V42S030, username=laode, pid=48826) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 244, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:04:40,994 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:04:41,001 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:04:46,280 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:04:50,690 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:04:51,949 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:04:51,969 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:05:05,135 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:05:13,375 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:05:13,528 - INFO - [pid 48837] Worker Worker(salt=9340185522, workers=5, host=DESKTOP-V42S030, username=laode, pid=48826) done      Extract()
2024-03-22 02:05:17,283 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 02:05:17,400 - INFO - LOAD airports_data - SUCCESS
2024-03-22 02:08:00,510 - INFO - LOAD bookings - SUCCESS
2024-03-22 02:12:36,785 - ERROR - [pid 49395] Worker Worker(salt=9340185522, workers=5, host=DESKTOP-V42S030, username=laode, pid=48826) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 244, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:21:15,718 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:21:15,723 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:21:20,661 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:21:24,944 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:21:26,767 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:21:26,790 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:21:41,942 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:21:54,466 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:21:54,792 - INFO - [pid 59301] Worker Worker(salt=7042050129, workers=5, host=DESKTOP-V42S030, username=laode, pid=59285) done      Extract()
2024-03-22 02:22:00,285 - ERROR - [pid 59930] Worker Worker(salt=7042050129, workers=5, host=DESKTOP-V42S030, username=laode, pid=59285) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 113, in run
    cur_dwh.execute(upsert_aircrafts_data_query.format(
psycopg2.errors.UndefinedTable: relation "stg.aircrafts_data" does not exist
LINE 1: INSERT INTO stg.aircrafts_data 
                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:31:18,849 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:31:18,860 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:31:23,680 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:31:28,998 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:31:30,616 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:31:30,642 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:31:46,641 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:31:57,025 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:31:57,217 - INFO - [pid 64830] Worker Worker(salt=7485961681, workers=5, host=DESKTOP-V42S030, username=laode, pid=64819) done      Extract()
2024-03-22 02:32:01,882 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-22 02:32:02,008 - INFO - LOAD airports_data - SUCCESS
2024-03-22 02:34:30,109 - INFO - LOAD bookings - SUCCESS
2024-03-22 02:38:35,185 - ERROR - [pid 65455] Worker Worker(salt=7485961681, workers=5, host=DESKTOP-V42S030, username=laode, pid=64819) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 244, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:42:05,038 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:42:05,045 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:42:10,531 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:42:16,483 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:42:17,927 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:42:17,950 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:42:33,722 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:42:42,326 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:42:42,476 - INFO - [pid 72651] Worker Worker(salt=9677362297, workers=5, host=DESKTOP-V42S030, username=laode, pid=72635) done      Extract()
2024-03-22 02:46:51,374 - ERROR - [pid 73329] Worker Worker(salt=9677362297, workers=5, host=DESKTOP-V42S030, username=laode, pid=72635) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 244, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 406, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:51:32,604 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:51:32,610 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:51:37,738 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:51:43,104 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:51:44,965 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:51:44,999 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:52:00,648 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:52:09,175 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:52:09,295 - INFO - [pid 79106] Worker Worker(salt=6897779403, workers=5, host=DESKTOP-V42S030, username=laode, pid=79094) done      Extract()
2024-03-22 02:52:14,211 - INFO - LOAD seats - SUCCESS
2024-03-22 02:52:14,253 - ERROR - [pid 79710] Worker Worker(salt=6897779403, workers=5, host=DESKTOP-V42S030, username=laode, pid=79094) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 275, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:54:23,641 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:54:23,647 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:54:29,076 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:54:34,755 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:54:36,421 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:54:36,450 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:54:53,320 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:55:02,140 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:55:02,318 - INFO - [pid 80911] Worker Worker(salt=7539564449, workers=5, host=DESKTOP-V42S030, username=laode, pid=80894) done      Extract()
2024-03-22 02:55:06,010 - ERROR - [pid 81559] Worker Worker(salt=7539564449, workers=5, host=DESKTOP-V42S030, username=laode, pid=80894) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 269, in run
    cur_dwh.execute(upsert_boarding_passes_query.format(
psycopg2.errors.ForeignKeyViolation: insert or update on table "boarding_passes" violates foreign key constraint "boarding_passes_ticket_no_fkey"
DETAIL:  Key (ticket_no, flight_id)=(5435212351   , 30625) is not present in table "ticket_flights".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:56:29,116 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:56:29,122 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:56:33,828 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:56:39,329 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:56:40,675 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:56:40,706 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:56:56,858 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:57:04,736 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:57:04,865 - INFO - [pid 82310] Worker Worker(salt=6245021130, workers=5, host=DESKTOP-V42S030, username=laode, pid=82299) done      Extract()
2024-03-22 02:57:08,639 - ERROR - [pid 82872] Worker Worker(salt=6245021130, workers=5, host=DESKTOP-V42S030, username=laode, pid=82299) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 269, in run
    cur_dwh.execute(upsert_ticket_flights_query.format(
psycopg2.errors.ForeignKeyViolation: insert or update on table "ticket_flights" violates foreign key constraint "ticket_flights_flight_id_fkey"
DETAIL:  Key (flight_id)=(30625) is not present in table "flights".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 02:58:24,359 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 02:58:24,365 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 02:58:29,146 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 02:58:36,216 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 02:58:37,799 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 02:58:37,824 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 02:58:54,643 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 02:59:03,657 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 02:59:03,786 - INFO - [pid 83582] Worker Worker(salt=9468726272, workers=5, host=DESKTOP-V42S030, username=laode, pid=83571) done      Extract()
2024-03-22 02:59:07,502 - ERROR - [pid 84202] Worker Worker(salt=9468726272, workers=5, host=DESKTOP-V42S030, username=laode, pid=83571) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 275, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "flight_id" of relation "bookings" does not exist
LINE 2:     (flight_id, flight_no, scheduled_departure, scheduled_ar...
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:01:39,484 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:01:39,489 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:01:44,884 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:01:50,633 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:01:52,458 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:01:52,487 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:02:09,455 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:02:17,976 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:02:18,093 - INFO - [pid 85657] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) done      Extract()
2024-03-22 03:02:21,918 - ERROR - [pid 86283] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 275, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:01:39,484 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:01:39,489 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:01:44,884 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:01:50,633 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:01:52,458 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:01:52,487 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:02:09,455 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:02:17,976 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:02:18,093 - INFO - [pid 85657] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) done      Extract()
2024-03-22 03:02:21,918 - ERROR - [pid 86283] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 275, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:12:47,243 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:12:47,248 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:12:52,602 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:12:58,590 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:13:00,967 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:13:01,004 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:13:17,675 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:13:25,575 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:13:25,710 - INFO - [pid 90853] Worker Worker(salt=2240939448, workers=5, host=DESKTOP-V42S030, username=laode, pid=90842) done      Extract()
2024-03-22 03:13:29,092 - ERROR - [pid 91490] Worker Worker(salt=2240939448, workers=5, host=DESKTOP-V42S030, username=laode, pid=90842) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 276, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "None"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'None', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 408, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:01:39,484 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:01:39,489 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:01:44,884 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:01:50,633 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:01:52,458 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:01:52,487 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:02:09,455 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:02:17,976 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:02:18,093 - INFO - [pid 85657] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) done      Extract()
2024-03-22 03:02:21,918 - ERROR - [pid 86283] Worker Worker(salt=6119576870, workers=5, host=DESKTOP-V42S030, username=laode, pid=85646) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 275, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 407, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:12:47,243 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:12:47,248 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:12:52,602 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:12:58,590 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:13:00,967 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:13:01,004 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:13:17,675 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:13:25,575 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:13:25,710 - INFO - [pid 90853] Worker Worker(salt=2240939448, workers=5, host=DESKTOP-V42S030, username=laode, pid=90842) done      Extract()
2024-03-22 03:13:29,092 - ERROR - [pid 91490] Worker Worker(salt=2240939448, workers=5, host=DESKTOP-V42S030, username=laode, pid=90842) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 276, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "None"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'None', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 408, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:16:29,873 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:16:29,880 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:16:35,466 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:16:41,492 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:16:42,897 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:16:42,923 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:16:59,112 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:17:07,041 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:17:07,160 - INFO - [pid 93053] Worker Worker(salt=3388462846, workers=5, host=DESKTOP-V42S030, username=laode, pid=93017) done      Extract()
2024-03-22 03:17:10,549 - ERROR - [pid 93649] Worker Worker(salt=3388462846, workers=5, host=DESKTOP-V42S030, username=laode, pid=93017) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 276, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', None, None...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 408, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:30:45,034 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:30:45,040 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:30:50,615 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:30:54,487 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:30:55,465 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:30:55,486 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:31:11,666 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:31:22,736 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:31:22,878 - INFO - [pid 99722] Worker Worker(salt=391549434, workers=5, host=DESKTOP-V42S030, username=laode, pid=99711) done      Extract()
2024-03-22 03:31:27,578 - ERROR - [pid 100265] Worker Worker(salt=391549434, workers=5, host=DESKTOP-V42S030, username=laode, pid=99711) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 276, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near "\"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', \N, \N, '2...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 408, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:32:22,258 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:32:22,264 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:32:27,341 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:32:31,776 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:32:33,396 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:32:33,429 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:32:50,400 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:33:00,316 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:33:00,499 - INFO - [pid 100866] Worker Worker(salt=3451350464, workers=5, host=DESKTOP-V42S030, username=laode, pid=100856) done      Extract()
2024-03-22 03:33:05,300 - ERROR - [pid 101507] Worker Worker(salt=3451350464, workers=5, host=DESKTOP-V42S030, username=laode, pid=100856) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 276, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "\N"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', '\N', '\N'...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 408, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:51:55,993 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:51:55,999 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:52:01,116 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:52:05,345 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:52:06,598 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:52:06,622 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:52:24,222 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:52:34,577 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:52:34,697 - INFO - [pid 109400] Worker Worker(salt=8106331995, workers=5, host=DESKTOP-V42S030, username=laode, pid=109389) done      Extract()
2024-03-22 03:52:38,578 - ERROR - [pid 110023] Worker Worker(salt=8106331995, workers=5, host=DESKTOP-V42S030, username=laode, pid=109389) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 03:58:11,956 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 03:58:11,963 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 03:58:17,145 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 03:58:21,199 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 03:58:22,341 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 03:58:22,357 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 03:58:37,502 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 03:58:46,239 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 03:58:46,382 - INFO - [pid 112510] Worker Worker(salt=1285327645, workers=5, host=DESKTOP-V42S030, username=laode, pid=112499) done      Extract()
2024-03-22 03:58:50,153 - ERROR - [pid 113075] Worker Worker(salt=1285327645, workers=5, host=DESKTOP-V42S030, username=laode, pid=112499) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', None, None...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:00:44,349 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:00:44,356 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:00:49,207 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:00:53,603 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:00:55,293 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:00:55,322 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:01:10,476 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:01:19,702 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:01:19,839 - INFO - [pid 114268] Worker Worker(salt=7236672167, workers=5, host=DESKTOP-V42S030, username=laode, pid=114254) done      Extract()
2024-03-22 04:01:24,015 - ERROR - [pid 114822] Worker Worker(salt=7236672167, workers=5, host=DESKTOP-V42S030, username=laode, pid=114254) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near ","
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', , , '2017-...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:00:44,349 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:00:44,356 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:00:49,207 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:00:53,603 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:00:55,293 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:00:55,322 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:01:10,476 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:01:19,702 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:01:19,839 - INFO - [pid 114268] Worker Worker(salt=7236672167, workers=5, host=DESKTOP-V42S030, username=laode, pid=114254) done      Extract()
2024-03-22 04:01:24,015 - ERROR - [pid 114822] Worker Worker(salt=7236672167, workers=5, host=DESKTOP-V42S030, username=laode, pid=114254) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near ","
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', , , '2017-...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:03:52,080 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:03:52,087 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:03:57,029 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:04:02,708 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:04:04,153 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:04:04,185 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:04:20,422 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:04:30,482 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:04:30,609 - INFO - [pid 116604] Worker Worker(salt=6901672628, workers=5, host=DESKTOP-V42S030, username=laode, pid=116568) done      Extract()
2024-03-22 04:04:34,879 - ERROR - [pid 117190] Worker Worker(salt=6901672628, workers=5, host=DESKTOP-V42S030, username=laode, pid=116568) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near ","
LINE 4: ...:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319',  ,  , '2017...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:08:26,110 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:08:26,118 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:08:30,931 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:08:35,754 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:08:37,540 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:08:37,628 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:08:54,816 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:09:03,699 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:09:03,834 - INFO - [pid 119464] Worker Worker(salt=2843310507, workers=5, host=DESKTOP-V42S030, username=laode, pid=119453) done      Extract()
2024-03-22 04:09:07,948 - ERROR - [pid 120079] Worker Worker(salt=2843310507, workers=5, host=DESKTOP-V42S030, username=laode, pid=119453) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedColumn: column excluded.departure_ does not exist
LINE 20: ...         OR bookings.flights.departure_airport <> EXCLUDED.d...
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:10:07,559 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:10:07,565 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:10:12,854 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:10:17,724 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:10:19,149 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:10:19,173 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:10:35,579 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:10:45,458 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:10:45,591 - INFO - [pid 120892] Worker Worker(salt=3118674579, workers=5, host=DESKTOP-V42S030, username=laode, pid=120881) done      Extract()
2024-03-22 04:10:50,015 - ERROR - [pid 121501] Worker Worker(salt=3118674579, workers=5, host=DESKTOP-V42S030, username=laode, pid=120881) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "bookings"
LINE 29:                         bookings.bookings.updated_at
                                 ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:13:10,058 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:13:10,064 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:13:15,550 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:13:20,304 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:13:21,358 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:13:21,373 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:13:37,029 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:13:46,810 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:13:46,950 - INFO - [pid 122614] Worker Worker(salt=576994555, workers=5, host=DESKTOP-V42S030, username=laode, pid=122598) done      Extract()
2024-03-22 04:13:50,101 - ERROR - [pid 123418] Worker Worker(salt=576994555, workers=5, host=DESKTOP-V42S030, username=laode, pid=122598) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near "06"
LINE 4: ...0:00', 'DME', 'LED', 'Arrived', '321', 2017-07-16 06:44:00+0...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:15:25,121 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:15:25,127 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:15:30,469 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:15:34,373 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:15:35,883 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:15:35,916 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:15:52,335 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:16:01,031 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:16:01,158 - INFO - [pid 124218] Worker Worker(salt=6068321639, workers=5, host=DESKTOP-V42S030, username=laode, pid=124206) done      Extract()
2024-03-22 04:16:04,989 - ERROR - [pid 124805] Worker Worker(salt=6068321639, workers=5, host=DESKTOP-V42S030, username=laode, pid=124206) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:36:39,042 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:36:39,048 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:36:43,736 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:36:49,086 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:36:50,602 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:36:50,624 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:37:07,566 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:37:17,301 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:37:17,445 - INFO - [pid 133974] Worker Worker(salt=9675906355, workers=5, host=DESKTOP-V42S030, username=laode, pid=133964) done      Extract()
2024-03-22 04:37:21,808 - ERROR - [pid 134589] Worker Worker(salt=9675906355, workers=5, host=DESKTOP-V42S030, username=laode, pid=133964) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near "06"
LINE 4: ...0:00', 'DME', 'LED', 'Arrived', '321', 2017-07-16 06:44:00+0...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:36:39,042 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:36:39,048 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:36:43,736 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:36:49,086 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:36:50,602 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:36:50,624 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:37:07,566 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:37:17,301 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:37:17,445 - INFO - [pid 133974] Worker Worker(salt=9675906355, workers=5, host=DESKTOP-V42S030, username=laode, pid=133964) done      Extract()
2024-03-22 04:37:21,808 - ERROR - [pid 134589] Worker Worker(salt=9675906355, workers=5, host=DESKTOP-V42S030, username=laode, pid=133964) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.SyntaxError: syntax error at or near "06"
LINE 4: ...0:00', 'DME', 'LED', 'Arrived', '321', 2017-07-16 06:44:00+0...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:39:24,505 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:39:24,511 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:39:29,886 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:39:33,791 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:39:35,221 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:39:35,249 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:39:51,514 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:40:02,290 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:40:02,423 - INFO - [pid 135607] Worker Worker(salt=5640094729, workers=5, host=DESKTOP-V42S030, username=laode, pid=135596) done      Extract()
2024-03-22 04:40:06,854 - ERROR - [pid 136216] Worker Worker(salt=5640094729, workers=5, host=DESKTOP-V42S030, username=laode, pid=135596) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', NU...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:47:32,920 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:47:32,926 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:47:37,657 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:47:42,721 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:47:44,448 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:47:44,475 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:48:05,079 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:48:15,899 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:48:16,091 - INFO - [pid 139560] Worker Worker(salt=5714205974, workers=5, host=DESKTOP-V42S030, username=laode, pid=139549) done      Extract()
2024-03-22 04:48:20,152 - ERROR - [pid 140252] Worker Worker(salt=5714205974, workers=5, host=DESKTOP-V42S030, username=laode, pid=139549) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:47:32,920 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:47:32,926 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:47:37,657 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:47:42,721 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:47:44,448 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:47:44,475 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:48:05,079 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:48:15,899 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:48:16,091 - INFO - [pid 139560] Worker Worker(salt=5714205974, workers=5, host=DESKTOP-V42S030, username=laode, pid=139549) done      Extract()
2024-03-22 04:48:20,152 - ERROR - [pid 140252] Worker Worker(salt=5714205974, workers=5, host=DESKTOP-V42S030, username=laode, pid=139549) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:50:31,193 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:50:31,200 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:50:36,798 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:50:42,438 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:50:44,289 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:50:44,331 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:51:01,790 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:51:11,488 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:51:11,779 - INFO - [pid 141559] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) done      Extract()
2024-03-22 04:51:16,473 - ERROR - [pid 142203] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:50:31,193 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:50:31,200 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:50:36,798 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:50:42,438 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:50:44,289 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:50:44,331 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:51:01,790 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:51:11,488 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:51:11,779 - INFO - [pid 141559] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) done      Extract()
2024-03-22 04:51:16,473 - ERROR - [pid 142203] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:52:45,749 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:52:45,755 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:52:51,034 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:52:55,300 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:52:56,798 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:52:56,821 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:53:13,288 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:53:22,190 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:53:22,333 - INFO - [pid 143017] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Extract()
2024-03-22 04:54:01,052 - INFO - LOAD flights - SUCCESS
2024-03-22 05:16:47,116 - INFO - LOAD ticket_flights - SUCCESS
2024-03-22 05:26:56,899 - INFO - LOAD boarding_passes - SUCCESS
2024-03-22 05:26:57,624 - INFO - [pid 143624] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Load()
2024-03-22 04:50:31,193 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:50:31,200 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:50:36,798 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:50:42,438 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:50:44,289 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:50:44,331 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:51:01,790 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:51:11,488 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:51:11,779 - INFO - [pid 141559] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) done      Extract()
2024-03-22 04:51:16,473 - ERROR - [pid 142203] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:52:45,749 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:52:45,755 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:52:51,034 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:52:55,300 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:52:56,798 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:52:56,821 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:53:13,288 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:53:22,190 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:53:22,333 - INFO - [pid 143017] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Extract()
2024-03-22 04:54:01,052 - INFO - LOAD flights - SUCCESS
2024-03-22 05:16:47,116 - INFO - LOAD ticket_flights - SUCCESS
2024-03-22 05:26:56,899 - INFO - LOAD boarding_passes - SUCCESS
2024-03-22 05:26:57,624 - INFO - [pid 143624] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Load()
2024-03-23 02:33:33,184 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 02:33:33,195 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 02:33:37,762 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 02:33:45,086 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 02:33:47,415 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 02:33:47,447 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 02:33:58,872 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 02:34:09,434 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 02:34:09,694 - INFO - [pid 48643] Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) done      Extract()
2024-03-23 02:34:09,696 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 02:34:09,703 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 02:34:09,704 - DEBUG - Asking scheduler for work...
2024-03-23 02:34:09,711 - DEBUG - Done
2024-03-23 02:34:09,711 - DEBUG - There are no more tasks to run at this time
2024-03-23 02:34:09,711 - INFO - Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) was stopped. Shutting down Keep-Alive thread
2024-03-23 02:34:09,714 - INFO - 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Extract()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-22 04:50:31,193 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:50:31,200 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:50:36,798 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:50:42,438 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:50:44,289 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:50:44,331 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:51:01,790 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:51:11,488 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:51:11,779 - INFO - [pid 141559] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) done      Extract()
2024-03-22 04:51:16,473 - ERROR - [pid 142203] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:52:45,749 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:52:45,755 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:52:51,034 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:52:55,300 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:52:56,798 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:52:56,821 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:53:13,288 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:53:22,190 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:53:22,333 - INFO - [pid 143017] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Extract()
2024-03-22 04:54:01,052 - INFO - LOAD flights - SUCCESS
2024-03-22 05:16:47,116 - INFO - LOAD ticket_flights - SUCCESS
2024-03-22 05:26:56,899 - INFO - LOAD boarding_passes - SUCCESS
2024-03-22 05:26:57,624 - INFO - [pid 143624] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Load()
2024-03-23 02:33:33,184 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 02:33:33,195 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 02:33:37,762 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 02:33:45,086 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 02:33:47,415 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 02:33:47,447 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 02:33:58,872 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 02:34:09,434 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 02:34:09,694 - INFO - [pid 48643] Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) done      Extract()
2024-03-23 02:34:09,696 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 02:34:09,703 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 02:34:09,704 - DEBUG - Asking scheduler for work...
2024-03-23 02:34:09,711 - DEBUG - Done
2024-03-23 02:34:09,711 - DEBUG - There are no more tasks to run at this time
2024-03-23 02:34:09,711 - INFO - Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) was stopped. Shutting down Keep-Alive thread
2024-03-23 02:34:09,714 - INFO - 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Extract()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-23 03:39:09,110 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 03:39:09,118 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 03:39:12,049 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 03:39:16,499 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 03:39:18,028 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 03:39:18,062 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 03:39:26,075 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 03:39:34,367 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 03:39:34,549 - INFO - [pid 75987] Worker Worker(salt=7228751460, workers=5, host=DESKTOP-V42S030, username=laode, pid=75974) done      Extract()
2024-03-23 03:39:37,686 - ERROR - [pid 76281] Worker Worker(salt=7228751460, workers=5, host=DESKTOP-V42S030, username=laode, pid=75974) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'created_at'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 110, in run
    created_at = row['created_at']
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1112, in __getitem__
    return self._get_value(key)
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1228, in _get_value
    loc = self.index.get_loc(label)
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'created_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:50:31,193 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:50:31,200 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:50:36,798 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:50:42,438 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:50:44,289 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:50:44,331 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:51:01,790 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:51:11,488 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:51:11,779 - INFO - [pid 141559] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) done      Extract()
2024-03-22 04:51:16,473 - ERROR - [pid 142203] Worker Worker(salt=1006975231, workers=5, host=DESKTOP-V42S030, username=laode, pid=141548) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 286, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "NULL"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'NULL', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 418, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-22 04:52:45,749 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-22 04:52:45,755 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-22 04:52:51,034 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-22 04:52:55,300 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-22 04:52:56,798 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-22 04:52:56,821 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-22 04:53:13,288 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-22 04:53:22,190 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-22 04:53:22,333 - INFO - [pid 143017] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Extract()
2024-03-22 04:54:01,052 - INFO - LOAD flights - SUCCESS
2024-03-22 05:16:47,116 - INFO - LOAD ticket_flights - SUCCESS
2024-03-22 05:26:56,899 - INFO - LOAD boarding_passes - SUCCESS
2024-03-22 05:26:57,624 - INFO - [pid 143624] Worker Worker(salt=054697758, workers=5, host=DESKTOP-V42S030, username=laode, pid=143006) done      Load()
2024-03-23 02:33:33,184 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 02:33:33,195 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 02:33:37,762 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 02:33:45,086 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 02:33:47,415 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 02:33:47,447 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 02:33:58,872 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 02:34:09,434 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 02:34:09,694 - INFO - [pid 48643] Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) done      Extract()
2024-03-23 02:34:09,696 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 02:34:09,703 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 02:34:09,704 - DEBUG - Asking scheduler for work...
2024-03-23 02:34:09,711 - DEBUG - Done
2024-03-23 02:34:09,711 - DEBUG - There are no more tasks to run at this time
2024-03-23 02:34:09,711 - INFO - Worker Worker(salt=2540432691, workers=1, host=DESKTOP-V42S030, username=laode, pid=48643) was stopped. Shutting down Keep-Alive thread
2024-03-23 02:34:09,714 - INFO - 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Extract()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-23 03:39:09,110 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 03:39:09,118 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 03:39:12,049 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 03:39:16,499 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 03:39:18,028 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 03:39:18,062 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 03:39:26,075 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 03:39:34,367 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 03:39:34,549 - INFO - [pid 75987] Worker Worker(salt=7228751460, workers=5, host=DESKTOP-V42S030, username=laode, pid=75974) done      Extract()
2024-03-23 03:39:37,686 - ERROR - [pid 76281] Worker Worker(salt=7228751460, workers=5, host=DESKTOP-V42S030, username=laode, pid=75974) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'created_at'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 110, in run
    created_at = row['created_at']
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1112, in __getitem__
    return self._get_value(key)
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1228, in _get_value
    loc = self.index.get_loc(label)
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'created_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 04:50:21,612 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 04:50:21,618 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 04:50:24,456 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 04:50:28,965 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 04:50:30,447 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 04:50:30,469 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 04:50:39,352 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 04:50:47,083 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 04:50:47,250 - INFO - [pid 99180] Worker Worker(salt=4045683650, workers=5, host=DESKTOP-V42S030, username=laode, pid=99151) done      Extract()
2024-03-23 04:50:50,074 - ERROR - [pid 99462] Worker Worker(salt=4045683650, workers=5, host=DESKTOP-V42S030, username=laode, pid=99151) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 114, in run
    cur_dwh.execute(upsert_aircrafts_data_query.format(
psycopg2.errors.UndefinedColumn: column aircrafts_data.updated_at does not exist
LINE 15:                         stg.aircrafts_data.updated_at
                                 ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 04:56:26,738 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 04:56:26,746 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 04:56:30,332 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 04:56:34,716 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 04:56:36,380 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 04:56:36,403 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 04:56:44,454 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 04:56:51,360 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 04:56:51,535 - INFO - [pid 103926] Worker Worker(salt=766799391, workers=1, host=DESKTOP-V42S030, username=laode, pid=103926) done      Extract()
2024-03-23 04:56:51,537 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 04:56:51,542 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 04:56:51,542 - DEBUG - Asking scheduler for work...
2024-03-23 04:56:51,548 - DEBUG - Pending tasks: 1
2024-03-23 04:56:51,548 - INFO - [pid 103926] Worker Worker(salt=766799391, workers=1, host=DESKTOP-V42S030, username=laode, pid=103926) running   Load()
2024-03-23 04:56:54,433 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-23 04:56:54,622 - INFO - LOAD airports_data - SUCCESS
2024-03-23 05:01:48,693 - INFO - LOAD bookings - SUCCESS
2024-03-23 05:09:50,273 - INFO - LOAD tickets - SUCCESS
2024-03-23 05:09:51,885 - INFO - LOAD seats - SUCCESS
2024-03-23 05:09:51,921 - ERROR - [pid 103926] Worker Worker(salt=766799391, workers=1, host=DESKTOP-V42S030, username=laode, pid=103926) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 289, in run
    created_at=created_at,
NameError: name 'created_at' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:09:51,973 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:09:51,982 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:09:51,982 - DEBUG - Asking scheduler for work...
2024-03-23 05:09:51,986 - DEBUG - Done
2024-03-23 05:09:51,986 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:09:51,986 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:09:51,986 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:09:51,986 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:09:51,987 - INFO - Worker Worker(salt=766799391, workers=1, host=DESKTOP-V42S030, username=laode, pid=103926) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:09:51,989 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:11:03,796 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:11:03,801 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:11:05,957 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:11:09,301 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:11:10,535 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:11:10,559 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:11:17,882 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:11:25,026 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:11:25,197 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) done      Extract()
2024-03-23 05:11:25,198 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:11:25,204 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:11:25,204 - DEBUG - Asking scheduler for work...
2024-03-23 05:11:25,209 - DEBUG - Pending tasks: 1
2024-03-23 05:11:25,209 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) running   Load()
2024-03-23 05:11:28,381 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-23 05:11:28,581 - INFO - LOAD airports_data - SUCCESS
2024-03-23 05:16:01,174 - INFO - LOAD bookings - SUCCESS
2024-03-23 05:22:54,944 - INFO - LOAD tickets - SUCCESS
2024-03-23 05:22:56,634 - INFO - LOAD seats - SUCCESS
2024-03-23 05:22:56,677 - ERROR - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "None"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'None', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:22:56,751 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:22:56,768 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:22:56,768 - DEBUG - Asking scheduler for work...
2024-03-23 05:22:56,777 - DEBUG - Done
2024-03-23 05:22:56,777 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:22:56,778 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:22:56,778 - INFO - Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:22:56,780 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:11:03,796 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:11:03,801 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:11:05,957 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:11:09,301 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:11:10,535 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:11:10,559 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:11:17,882 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:11:25,026 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:11:25,197 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) done      Extract()
2024-03-23 05:11:25,198 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:11:25,204 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:11:25,204 - DEBUG - Asking scheduler for work...
2024-03-23 05:11:25,209 - DEBUG - Pending tasks: 1
2024-03-23 05:11:25,209 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) running   Load()
2024-03-23 05:11:28,381 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-23 05:11:28,581 - INFO - LOAD airports_data - SUCCESS
2024-03-23 05:16:01,174 - INFO - LOAD bookings - SUCCESS
2024-03-23 05:22:54,944 - INFO - LOAD tickets - SUCCESS
2024-03-23 05:22:56,634 - INFO - LOAD seats - SUCCESS
2024-03-23 05:22:56,677 - ERROR - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "None"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'None', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:22:56,751 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:22:56,768 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:22:56,768 - DEBUG - Asking scheduler for work...
2024-03-23 05:22:56,777 - DEBUG - Done
2024-03-23 05:22:56,777 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:22:56,778 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:22:56,778 - INFO - Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:22:56,780 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:28:55,960 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:28:55,966 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:28:57,908 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:29:00,750 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:29:01,648 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:29:01,667 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:29:06,457 - INFO - Worker Worker(salt=1536265404, workers=1, host=DESKTOP-V42S030, username=laode, pid=122700) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:31:10,820 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:31:10,824 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:31:12,803 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:31:16,820 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:31:18,408 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:31:18,427 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:31:27,339 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:31:35,550 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:31:35,727 - INFO - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) done      Extract()
2024-03-23 05:31:35,729 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:31:35,735 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:31:35,736 - DEBUG - Asking scheduler for work...
2024-03-23 05:31:35,740 - DEBUG - Pending tasks: 1
2024-03-23 05:31:35,740 - INFO - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) running   Load()
2024-03-23 05:31:38,719 - ERROR - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:31:38,783 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:31:38,796 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:31:38,797 - DEBUG - Asking scheduler for work...
2024-03-23 05:31:38,802 - DEBUG - Done
2024-03-23 05:31:38,803 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:31:38,803 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:31:38,804 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:31:38,804 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:31:38,804 - INFO - Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:31:38,807 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:11:03,796 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:11:03,801 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:11:05,957 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:11:09,301 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:11:10,535 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:11:10,559 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:11:17,882 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:11:25,026 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:11:25,197 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) done      Extract()
2024-03-23 05:11:25,198 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:11:25,204 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:11:25,204 - DEBUG - Asking scheduler for work...
2024-03-23 05:11:25,209 - DEBUG - Pending tasks: 1
2024-03-23 05:11:25,209 - INFO - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) running   Load()
2024-03-23 05:11:28,381 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-23 05:11:28,581 - INFO - LOAD airports_data - SUCCESS
2024-03-23 05:16:01,174 - INFO - LOAD bookings - SUCCESS
2024-03-23 05:22:54,944 - INFO - LOAD tickets - SUCCESS
2024-03-23 05:22:56,634 - INFO - LOAD seats - SUCCESS
2024-03-23 05:22:56,677 - ERROR - [pid 112790] Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "None"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'None', 'N...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:22:56,751 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:22:56,768 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:22:56,768 - DEBUG - Asking scheduler for work...
2024-03-23 05:22:56,777 - DEBUG - Done
2024-03-23 05:22:56,777 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:22:56,777 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:22:56,778 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:22:56,778 - INFO - Worker Worker(salt=6795494932, workers=1, host=DESKTOP-V42S030, username=laode, pid=112790) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:22:56,780 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:28:55,960 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:28:55,966 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:28:57,908 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:29:00,750 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:29:01,648 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:29:01,667 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:29:06,457 - INFO - Worker Worker(salt=1536265404, workers=1, host=DESKTOP-V42S030, username=laode, pid=122700) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:31:10,820 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:31:10,824 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:31:12,803 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:31:16,820 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:31:18,408 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:31:18,427 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:31:27,339 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:31:35,550 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:31:35,727 - INFO - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) done      Extract()
2024-03-23 05:31:35,729 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:31:35,735 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:31:35,736 - DEBUG - Asking scheduler for work...
2024-03-23 05:31:35,740 - DEBUG - Pending tasks: 1
2024-03-23 05:31:35,740 - INFO - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) running   Load()
2024-03-23 05:31:38,719 - ERROR - [pid 123882] Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) failed    Load()
Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 278, in run
    cur_dwh.execute(upsert_flights_query.format(
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp with time zone: "nan"
LINE 4: ...1:55:00+00:00', 'DME', 'BTK', 'Scheduled', '319', 'nan', 'na...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/.venv/lib/python3.10/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/laode/pacmann/project/pacflight_data-pipeline-orchestration/pipeline/load.py", line 410, in run
    raise Exception('Failed to Load Tables')
Exception: Failed to Load Tables
2024-03-23 05:31:38,783 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:31:38,796 - INFO - Informed scheduler that task   Load__99914b932b   has status   FAILED
2024-03-23 05:31:38,797 - DEBUG - Asking scheduler for work...
2024-03-23 05:31:38,802 - DEBUG - Done
2024-03-23 05:31:38,803 - DEBUG - There are no more tasks to run at this time
2024-03-23 05:31:38,803 - DEBUG - There are 1 pending tasks possibly being run by other workers
2024-03-23 05:31:38,804 - DEBUG - There are 1 pending tasks unique to this worker
2024-03-23 05:31:38,804 - DEBUG - There are 1 pending tasks last scheduled by this worker
2024-03-23 05:31:38,804 - INFO - Worker Worker(salt=7821149746, workers=1, host=DESKTOP-V42S030, username=laode, pid=123882) was stopped. Shutting down Keep-Alive thread
2024-03-23 05:31:38,807 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 Extract()
* 1 failed:
    - 1 Load()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2024-03-23 05:35:12,092 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 05:35:12,100 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 05:35:14,296 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 05:35:17,432 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 05:35:18,483 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 05:35:18,499 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 05:35:25,629 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 05:35:32,508 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 05:35:32,666 - INFO - [pid 126282] Worker Worker(salt=8292405135, workers=1, host=DESKTOP-V42S030, username=laode, pid=126282) done      Extract()
2024-03-23 05:35:32,668 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 05:35:32,673 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 05:35:32,673 - DEBUG - Asking scheduler for work...
2024-03-23 05:35:32,678 - DEBUG - Pending tasks: 1
2024-03-23 05:35:32,678 - INFO - [pid 126282] Worker Worker(salt=8292405135, workers=1, host=DESKTOP-V42S030, username=laode, pid=126282) running   Load()
2024-03-23 05:36:22,698 - INFO - LOAD flights - SUCCESS
2024-03-23 05:57:00,086 - INFO - LOAD ticket_flights - SUCCESS
2024-03-23 10:35:06,302 - INFO - LOAD boarding_passes - SUCCESS
2024-03-23 10:35:06,518 - INFO - [pid 126282] Worker Worker(salt=8292405135, workers=1, host=DESKTOP-V42S030, username=laode, pid=126282) done      Load()
2024-03-23 10:35:06,520 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 10:35:06,526 - INFO - Informed scheduler that task   Load__99914b932b   has status   DONE
2024-03-23 10:35:06,526 - DEBUG - Asking scheduler for work...
2024-03-23 10:35:06,530 - DEBUG - Done
2024-03-23 10:35:06,530 - DEBUG - There are no more tasks to run at this time
2024-03-23 10:35:06,530 - INFO - Worker Worker(salt=8292405135, workers=1, host=DESKTOP-V42S030, username=laode, pid=126282) was stopped. Shutting down Keep-Alive thread
2024-03-23 10:35:06,533 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 ran successfully:
    - 1 Extract()
    - 1 Load()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-23 11:05:22,613 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 11:05:22,619 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 11:05:24,594 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 11:05:27,377 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 11:05:28,515 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 11:05:28,537 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 11:05:37,341 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 11:05:45,022 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 11:05:45,224 - INFO - [pid 162221] Worker Worker(salt=3773767824, workers=1, host=DESKTOP-V42S030, username=laode, pid=162221) done      Extract()
2024-03-23 11:05:45,226 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 11:05:45,231 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 11:05:45,232 - DEBUG - Asking scheduler for work...
2024-03-23 11:05:45,236 - DEBUG - Pending tasks: 1
2024-03-23 11:05:45,237 - INFO - [pid 162221] Worker Worker(salt=3773767824, workers=1, host=DESKTOP-V42S030, username=laode, pid=162221) running   Load()
2024-03-23 11:05:48,593 - INFO - LOAD aircrafts_data - SUCCESS
2024-03-23 11:05:48,827 - INFO - LOAD airports_data - SUCCESS
2024-03-23 11:11:05,575 - INFO - LOAD bookings - SUCCESS
2024-03-23 11:18:29,341 - INFO - LOAD tickets - SUCCESS
2024-03-23 11:18:30,692 - INFO - LOAD seats - SUCCESS
2024-03-23 11:19:15,122 - INFO - LOAD flights - SUCCESS
2024-03-23 11:38:49,947 - INFO - LOAD ticket_flights - SUCCESS
2024-03-23 11:50:30,068 - INFO - LOAD boarding_passes - SUCCESS
2024-03-23 11:50:30,664 - INFO - [pid 162221] Worker Worker(salt=3773767824, workers=1, host=DESKTOP-V42S030, username=laode, pid=162221) done      Load()
2024-03-23 11:50:30,668 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 11:50:30,679 - INFO - Informed scheduler that task   Load__99914b932b   has status   DONE
2024-03-23 11:50:30,680 - DEBUG - Asking scheduler for work...
2024-03-23 11:50:30,684 - DEBUG - Done
2024-03-23 11:50:30,685 - DEBUG - There are no more tasks to run at this time
2024-03-23 11:50:30,686 - INFO - Worker Worker(salt=3773767824, workers=1, host=DESKTOP-V42S030, username=laode, pid=162221) was stopped. Shutting down Keep-Alive thread
2024-03-23 11:50:30,693 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 ran successfully:
    - 1 Extract()
    - 1 Load()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

2024-03-23 16:57:11,232 - INFO - EXTRACT 'bookings.aircrafts_data' - SUCCESS.
2024-03-23 16:57:11,239 - INFO - EXTRACT 'bookings.airports_data' - SUCCESS.
2024-03-23 16:57:13,007 - INFO - EXTRACT 'bookings.boarding_passes' - SUCCESS.
2024-03-23 16:57:15,435 - INFO - EXTRACT 'bookings.bookings' - SUCCESS.
2024-03-23 16:57:16,252 - INFO - EXTRACT 'bookings.flights' - SUCCESS.
2024-03-23 16:57:16,268 - INFO - EXTRACT 'bookings.seats' - SUCCESS.
2024-03-23 16:57:21,335 - INFO - EXTRACT 'bookings.ticket_flights' - SUCCESS.
2024-03-23 16:57:26,942 - INFO - EXTRACT 'bookings.tickets' - SUCCESS.
2024-03-23 16:57:27,065 - INFO - [pid 275335] Worker Worker(salt=3294872935, workers=1, host=DESKTOP-V42S030, username=laode, pid=275335) done      Extract()
2024-03-23 16:57:27,067 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 16:57:27,071 - INFO - Informed scheduler that task   Extract__99914b932b   has status   DONE
2024-03-23 16:57:27,071 - DEBUG - Asking scheduler for work...
2024-03-23 16:57:27,075 - DEBUG - Pending tasks: 1
2024-03-23 16:57:27,075 - INFO - [pid 275335] Worker Worker(salt=3294872935, workers=1, host=DESKTOP-V42S030, username=laode, pid=275335) running   Load()
2024-03-23 17:00:06,193 - INFO - LOAD bookings - SUCCESS
2024-03-23 17:00:06,235 - INFO - [pid 275335] Worker Worker(salt=3294872935, workers=1, host=DESKTOP-V42S030, username=laode, pid=275335) done      Load()
2024-03-23 17:00:06,235 - DEBUG - 1 running tasks, waiting for next task to finish
2024-03-23 17:00:06,238 - INFO - Informed scheduler that task   Load__99914b932b   has status   DONE
2024-03-23 17:00:06,238 - DEBUG - Asking scheduler for work...
2024-03-23 17:00:06,240 - DEBUG - Done
2024-03-23 17:00:06,241 - DEBUG - There are no more tasks to run at this time
2024-03-23 17:00:06,241 - INFO - Worker Worker(salt=3294872935, workers=1, host=DESKTOP-V42S030, username=laode, pid=275335) was stopped. Shutting down Keep-Alive thread
2024-03-23 17:00:06,242 - INFO - 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 ran successfully:
    - 1 Extract()
    - 1 Load()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

